--------------------------------------------------------
--  Flughafen Datenbank   
--------------------------------------------------------
--------------------------------------------------------
--  Drop Flughafen Datenbank   
--------------------------------------------------------
DROP TABLE "ABTEILUNG" CASCADE CONSTRAINTS;
DROP TABLE "BODENPERSONAL" CASCADE CONSTRAINTS;
DROP TABLE "CREW" CASCADE CONSTRAINTS;
DROP TABLE "DIENSTRANG" CASCADE CONSTRAINTS;
DROP TABLE "FLUG" CASCADE CONSTRAINTS;
DROP TABLE "FLUGHAFEN" CASCADE CONSTRAINTS;
DROP TABLE "FLUGLINIE" CASCADE CONSTRAINTS;
DROP TABLE "FLUGPERSONAL" CASCADE CONSTRAINTS;
DROP TABLE "FLUGZEUG" CASCADE CONSTRAINTS;
DROP TABLE "FLUGZEUGTYP" CASCADE CONSTRAINTS;
DROP TABLE "GATE" CASCADE CONSTRAINTS;
DROP TABLE "GEHALTSSTUFE" CASCADE CONSTRAINTS;
DROP TABLE "GEPAECK" CASCADE CONSTRAINTS;
DROP TABLE "LAND" CASCADE CONSTRAINTS;
DROP TABLE "ORT" CASCADE CONSTRAINTS;
DROP TABLE "PASSAGIERLISTE" CASCADE CONSTRAINTS;
DROP TABLE "PERSON" CASCADE CONSTRAINTS;
DROP TABLE "PERSONAL" CASCADE CONSTRAINTS;
DROP TABLE "REISEPASS" CASCADE CONSTRAINTS;
